In [2]:
import numpy as np
import pandas as pd

### Numpy Data Types
Numpy has the following data types: 
- ```int```
- ```float```
- ```complex```
- ```bool```
- ```string```
- ```unicode```
- ```object```

The numeric data types have various precisions like 32-bit or 64-bit. 

Numpy data types can be represented using either __Type__ or __Type Code__

In [3]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

Data types can be defined at creating the numpy array and converted to other types later. 

You can use either _type, type code_ or _```np``` dot_ methods to define the data type of an array, but when you use ```np``` dot method to define the data type, it can only follow _type_ rather than _type code_.

In [5]:
arr = np.array([1,2,3], dtype='f4')
print(arr)
arr.dtype

[1. 2. 3.]


dtype('float32')

In [6]:
# Identical to the above
arr = np.array([1,2,3], dtype=np.float32)
print(arr)
arr.dtype

[1. 2. 3.]


dtype('float32')

In [20]:
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
print(arr)
arr.dtype

[1.+2.j 3.-4.j]


dtype('complex64')

In [21]:
# Identical to the above
arr = np.array([1+2j, 3-4j], dtype='c8')
print(arr)
arr.dtype

[1.+2.j 3.-4.j]


dtype('complex64')

In [22]:
# ERROR
arr = np.array([1+2j, 3-4j], dtype=np.c8)
print(arr)
arr.dtype

AttributeError: module 'numpy' has no attribute 'c8'

In [ ]:
.astype --> for conversion

### Type Conversion

```astype``` method: convert the data type of an array to other data types. 

Notice that ```astype``` returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [23]:
arr = np.array([1,2,3], dtype='int16')
print(arr)
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32)
print(arr)
print('Data Type After Conversion: ' + str(arr.dtype))

[1 2 3]
Original Data Type: int16
[1. 2. 3.]
Data Type After Conversion: float32
