In [1]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array(range(20))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### Create an array with specified data type

In [5]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
print(arr)
print('\n','Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]

 Data Type: int8


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [6]:
# np.arange(start, stop, step)
arr = np.arange(0,20,3)
print(arr)

[ 0  3  6  9 12 15 18]


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [36]:
arr, step_size = np.linspace(0, 10, 20, endpoint=False, retstep=True)
print(arr)
print("\n "'The step size is ' + str(step_size))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]

 The step size is 0.5


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [8]:
arr = np.random.rand(3, 3)
print(arr)

[[0.75043457 0.34585826 0.51463065]
 [0.78279818 0.44574241 0.04984943]
 [0.03706984 0.87392522 0.33491141]]


In [41]:
arr = np.random.randn(3, 3)
print(arr)

[[-1.42443269  1.25422037  1.80490416]
 [ 0.36256069 -0.92056103  1.74348984]
 [-2.78408556  0.13523659 -0.62492066]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [44]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.float16)
print(arr)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [48]:
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type: float16


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [55]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [52]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.float16)
ones = np.ones_like(arr)
print("\n", arr,"\n"*2)
print(ones)
print('Data Type: ' + str(ones.dtype))


 [[1. 2. 3.]
 [4. 5. 6.]] 


[[1. 1. 1.]
 [1. 1. 1.]]
Data Type: float16


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [54]:
full = np.ones((4,4), 1)
print(full)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)

full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [60]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
arr

[[0, 1, 2], [3, 4, 5]]

In [63]:
print(np.repeat(arr, 3, axis = 1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [64]:
print(np.repeat(arr, 3, axis = 0))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [16]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [17]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))    

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [18]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### Create an array with given values on the diagonal

In [20]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print("\n",'Values on the diagonal: ' + str(np.diag(arr)))

[[0.98546817 0.65646884 0.45382218 0.04862072 0.51865363]
 [0.16055678 0.32062202 0.18133356 0.12109555 0.2904089 ]
 [0.92474379 0.42895492 0.60818766 0.14503429 0.81057987]
 [0.9130318  0.42431142 0.61254106 0.31249268 0.4594906 ]
 [0.73388655 0.56678598 0.18650267 0.63318633 0.00547298]]

 Values on the diagonal: [0.98546817 0.32062202 0.60818766 0.31249268 0.00547298]


In [21]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
