In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)
arr

array([[0.85437795, 0.1485011 , 0.13858   , 0.90844438, 0.87336941],
       [0.17978553, 0.86743414, 0.5521273 , 0.69833469, 0.45763573],
       [0.97860236, 0.49726308, 0.51907722, 0.22106386, 0.07079475],
       [0.34004275, 0.82460196, 0.16004258, 0.39806216, 0.80266628],
       [0.9595465 , 0.89638572, 0.96145272, 0.28021248, 0.11599335]])

### element-wise addition, subtraction, multiplication and division

In [3]:
print(arr + 10)
print('\n','-'*20)

[[10.85437795 10.1485011  10.13858    10.90844438 10.87336941]
 [10.17978553 10.86743414 10.5521273  10.69833469 10.45763573]
 [10.97860236 10.49726308 10.51907722 10.22106386 10.07079475]
 [10.34004275 10.82460196 10.16004258 10.39806216 10.80266628]
 [10.9595465  10.89638572 10.96145272 10.28021248 10.11599335]]

 --------------------


In [4]:
print(arr - 10)
print('\n','-'*20)


[[-9.14562205 -9.8514989  -9.86142    -9.09155562 -9.12663059]
 [-9.82021447 -9.13256586 -9.4478727  -9.30166531 -9.54236427]
 [-9.02139764 -9.50273692 -9.48092278 -9.77893614 -9.92920525]
 [-9.65995725 -9.17539804 -9.83995742 -9.60193784 -9.19733372]
 [-9.0404535  -9.10361428 -9.03854728 -9.71978752 -9.88400665]]

 --------------------


In [5]:
print(arr * 10)
print('\n','-'*20)


[[8.54377952 1.48501099 1.38580003 9.08444382 8.73369414]
 [1.79785529 8.67434143 5.521273   6.98334689 4.57635734]
 [9.78602364 4.97263077 5.19077216 2.21063862 0.70794754]
 [3.40042755 8.24601963 1.60042576 3.98062158 8.02666278]
 [9.59546499 8.96385721 9.61452719 2.8021248  1.1599335 ]]

 --------------------


In [6]:
print(arr / 10)
print('\n','-'*20)

[[0.0854378  0.01485011 0.013858   0.09084444 0.08733694]
 [0.01797855 0.08674341 0.05521273 0.06983347 0.04576357]
 [0.09786024 0.04972631 0.05190772 0.02210639 0.00707948]
 [0.03400428 0.0824602  0.01600426 0.03980622 0.08026663]
 [0.09595465 0.08963857 0.09614527 0.02802125 0.01159934]]

 --------------------


In [12]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [22]:
arr1 = np.random.rand(2,3)
arr1

array([[0.39732336, 0.53978371, 0.85364417],
       [0.67545934, 0.65183304, 0.96160493]])

In [23]:
np.add(arr1, [[8,9],[1,2]], out=arr1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) (2,3) 

In [13]:
np.add(arr1, [[8,9,10]], out=arr1)
print('\n',arr1)


 [ 9 11 13]


In [16]:

np.subtract(arr1, [8,9,10], out=arr1)
print('\n',arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print('\n',arr1)


 [1 2 3]

 [1 4 9]


### element-wise exponentiation

In [24]:
print(np.exp(arr))

[[2.34991217 1.16009407 1.14864157 2.48046088 2.39496691]
 [1.19696062 2.38079423 1.73694409 2.01040197 1.58033324]
 [2.6607349  1.64421502 1.68047622 1.24740309 1.0733609 ]
 [1.40500766 2.28097267 1.17356084 1.48893658 2.23148276]
 [2.61051234 2.45072946 2.61549329 1.32341098 1.1229884 ]]


### element-wise logorithm

In [25]:
# natural log
print(np.log(arr))      

[[-0.15738162 -1.90716292 -1.97630748 -0.09602161 -0.13539666]
 [-1.71599065 -0.14221569 -0.59397664 -0.35905679 -0.78168175]
 [-0.02162988 -0.69863606 -0.65570263 -1.50930365 -2.64797038]
 [-1.07868392 -0.19285448 -1.8323154  -0.92114711 -0.21981625]
 [-0.0412945  -0.10938447 -0.03930989 -1.27220711 -2.15422241]]


In [26]:
# base 2
print(np.log2(arr))     

[[-0.22705368 -2.75145449 -2.851209   -0.1385299  -0.19533609]
 [-2.47565119 -0.20517386 -0.85692716 -0.51800946 -1.12772839]
 [-0.03120533 -1.00791878 -0.94597893 -2.1774649  -3.82021374]
 [-1.55621194 -0.2782302  -2.64347234 -1.32893437 -0.31712781]
 [-0.05957537 -0.15780843 -0.05671218 -1.83540689 -3.10788599]]


In [27]:
# base 10
print(np.log10(arr))    

[[-0.06834997 -0.82827033 -0.85829943 -0.04170166 -0.05880202]
 [-0.74524527 -0.06176349 -0.25796078 -0.15593638 -0.33948007]
 [-0.00939374 -0.30341379 -0.28476803 -0.65548225 -1.14999892]
 [-0.46846647 -0.08375564 -0.79576447 -0.40004911 -0.09546498]
 [-0.01793397 -0.04750507 -0.01707207 -0.55251253 -0.93556691]]


### element-wise square root

In [28]:
print(np.sqrt(arr))

[[0.92432567 0.3853584  0.37226335 0.95312349 0.93454236]
 [0.42401124 0.93136145 0.74305269 0.83566422 0.67648779]
 [0.98924333 0.70516883 0.72047014 0.47017429 0.26607284]
 [0.58313185 0.90807597 0.40005322 0.63092167 0.89591645]
 [0.97956444 0.94677649 0.98053695 0.529351   0.34057797]]


In [ ]:
Axis = 0 #rows
Axis = 1 #columns

### sum along a specified axis

In [31]:
0.85437795+0.17978553+0.97860236+0.34004275+0.9595465

3.31235509

In [29]:
arr

array([[0.85437795, 0.1485011 , 0.13858   , 0.90844438, 0.87336941],
       [0.17978553, 0.86743414, 0.5521273 , 0.69833469, 0.45763573],
       [0.97860236, 0.49726308, 0.51907722, 0.22106386, 0.07079475],
       [0.34004275, 0.82460196, 0.16004258, 0.39806216, 0.80266628],
       [0.9595465 , 0.89638572, 0.96145272, 0.28021248, 0.11599335]])

In [30]:
# sum along the row
print(np.sum(arr, axis=0))    

[3.3123551  3.234186   2.33127981 2.50611757 2.32045953]


In [32]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.92327285 2.75531739 2.28680127 2.52541573 3.21359077]


In [33]:
0.85437795 +  0.1485011 + 0.13858 + 0.90844438 + 0.87336941

2.92327284

### compute the min and max along a specified axis

In [37]:
arr

array([[0.85437795, 0.1485011 , 0.13858   , 0.90844438, 0.87336941],
       [0.17978553, 0.86743414, 0.5521273 , 0.69833469, 0.45763573],
       [0.97860236, 0.49726308, 0.51907722, 0.22106386, 0.07079475],
       [0.34004275, 0.82460196, 0.16004258, 0.39806216, 0.80266628],
       [0.9595465 , 0.89638572, 0.96145272, 0.28021248, 0.11599335]])

In [34]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.17978553 0.1485011  0.13858    0.22106386 0.07079475]


In [35]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.90844438 0.86743414 0.97860236 0.82460196 0.96145272]


In [36]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.978602364480033
0.07079475371298494


### compute the mean

In [38]:
# compute the overall mean
print(np.mean(arr))

0.5481759206937319


In [39]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.66247102 0.6468372  0.46625596 0.50122351 0.46409191]


In [40]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.58465457 0.55106348 0.45736025 0.50508315 0.64271815]


### compute the median

In [41]:
# compute the overall median
print(np.median(arr))

0.519077216107838


In [42]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.85437795 0.82460196 0.51907722 0.39806216 0.45763573]


In [43]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.85437795 0.5521273  0.49726308 0.39806216 0.89638572]


### compute the percentile

In [71]:
a = np.random.seed(0)

In [73]:
arr1 = np.random.rand(10)
print(arr1,"\n")

[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
 0.0202184  0.83261985 0.77815675 0.87001215] 



In [53]:
arr1 = np.random.rand(10)
print(arr1,"\n")
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 67, 95,50]))

[0.07228874 0.65712214 0.15674268 0.81494132 0.39953903 0.3184659
 0.99736639 0.52511699 0.59521233 0.56355433] 

[0.11029301 0.59706963 0.91527511 0.54433566]


### compute the standard deviation & variance

In [74]:
# compute the overall standard deviation
print(np.std(arr))

0.31788985737439823


In [75]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.33525107 0.28748881 0.30216617 0.26178588 0.33407712]


In [76]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.36059927 0.23167063 0.31060052 0.26396697 0.36746933]


In [77]:
# compute the overall variance
print(np.var(arr))

0.10105396142151525


In [78]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.11239328 0.08264981 0.09130439 0.06853184 0.11160752]


In [79]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.13003184 0.05367128 0.09647269 0.06967856 0.13503371]


### compute cumulative sum & product

In [80]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.85437795 0.1485011  0.13858    0.90844438 0.87336941]
 [1.03416348 1.01593524 0.6907073  1.60677907 1.33100515]
 [2.01276585 1.51319832 1.20978452 1.82784293 1.4017999 ]
 [2.3528086  2.33780028 1.3698271  2.22590509 2.20446618]
 [3.3123551  3.234186   2.33127981 2.50611757 2.32045953]]


In [81]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.85437795 1.00287905 1.14145905 2.04990344 2.92327285]
 [0.17978553 1.04721967 1.59934697 2.29768166 2.75531739]
 [0.97860236 1.47586544 1.99494266 2.21600652 2.28680127]
 [0.34004275 1.16464472 1.32468729 1.72274945 2.52541573]
 [0.9595465  1.85593222 2.81738494 3.09759742 3.21359077]]


In [83]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[0.85437795 0.1485011  0.13858    0.90844438 0.87336941]
 [0.15360479 0.12881492 0.0765138  0.63439823 0.39968505]
 [0.15031801 0.06405491 0.03971657 0.14024252 0.0282956 ]
 [0.05111455 0.0528198  0.00635634 0.05582524 0.02271193]
 [0.04904679 0.04734691 0.00611132 0.01564293 0.00263443]]


In [84]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[0.85437795 0.12687606 0.01758249 0.01597271 0.01395008]
 [0.17978553 0.15595211 0.08610542 0.0601304  0.02751782]
 [0.97860236 0.48662282 0.25259482 0.05583959 0.00395315]
 [0.34004275 0.28039992 0.04487593 0.01786341 0.01433836]
 [0.9595465  0.86012378 0.82696835 0.23172685 0.02687877]]
