In [3]:
import numpy as np

In [24]:
arr = np.array(range(100)).reshape((10,10))

In [25]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [42]:
print(arr[5,5])

55


In [12]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [ ]:
print(arr[1:3, 4:6])

### boolean indexing

In [46]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [52]:
bools = np.array([True, True, False, False, False])
print(arr1[bools])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [53]:
# Akash :  Action #15th Jan
# check true/false across columns rather than rows? (axis = 1)

In [48]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### find elements/indices by conditions

In [ ]:
arr = np.arange(16).reshape(4,4)

In [ ]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

In [ ]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))