In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)
arr

array([[0.52956438, 0.23060221, 0.12726479, 0.57680471, 0.54369452],
       [0.35667434, 0.92517951, 0.8998306 , 0.7546117 , 0.64739461],
       [0.76344128, 0.04653736, 0.80889055, 0.35263131, 0.61589261],
       [0.50471896, 0.47907206, 0.70506564, 0.83199103, 0.64575149],
       [0.82359576, 0.47383837, 0.39582774, 0.31382977, 0.85757724]])

### sort an array along a specified axis

In [3]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.35667434 0.04653736 0.12726479 0.31382977 0.54369452]
 [0.50471896 0.23060221 0.39582774 0.35263131 0.61589261]
 [0.52956438 0.47383837 0.70506564 0.57680471 0.64575149]
 [0.76344128 0.47907206 0.80889055 0.7546117  0.64739461]
 [0.82359576 0.92517951 0.8998306  0.83199103 0.85757724]]


In [4]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.04653736 0.12726479 0.31382977 0.35667434 0.54369452]
 [0.23060221 0.35263131 0.39582774 0.50471896 0.61589261]
 [0.47383837 0.52956438 0.57680471 0.64575149 0.70506564]
 [0.47907206 0.64739461 0.7546117  0.76344128 0.80889055]
 [0.82359576 0.83199103 0.85757724 0.8998306  0.92517951]]
