In [1]:
import numpy as np

In [3]:
arr = np.random.rand(3,4)
arr

array([[0.51507518, 0.46963942, 0.86832863, 0.23844649],
       [0.55709017, 0.40476833, 0.27568408, 0.50893159],
       [0.01770405, 0.05787361, 0.03829712, 0.56271041]])

In [5]:
arr.T

array([[0.51507518, 0.55709017, 0.01770405],
       [0.46963942, 0.40476833, 0.05787361],
       [0.86832863, 0.27568408, 0.03829712],
       [0.23844649, 0.50893159, 0.56271041]])

### transpose an array

In [6]:
# the following methods return a copy
print(arr.T)
print('\n')
# or 
print(np.transpose(arr))
print('\n')
# or
print(arr.transpose())

[[0.51507518 0.55709017 0.01770405]
 [0.46963942 0.40476833 0.05787361]
 [0.86832863 0.27568408 0.03829712]
 [0.23844649 0.50893159 0.56271041]]


[[0.51507518 0.55709017 0.01770405]
 [0.46963942 0.40476833 0.05787361]
 [0.86832863 0.27568408 0.03829712]
 [0.23844649 0.50893159 0.56271041]]


[[0.51507518 0.55709017 0.01770405]
 [0.46963942 0.40476833 0.05787361]
 [0.86832863 0.27568408 0.03829712]
 [0.23844649 0.50893159 0.56271041]]


### flatten an array

In [9]:
# return a copy
flat_arr = arr.flatten()    
flat_arr

array([0.51507518, 0.46963942, 0.86832863, 0.23844649, 0.55709017,
       0.40476833, 0.27568408, 0.50893159, 0.01770405, 0.05787361,
       0.03829712, 0.56271041])

### append elements to an array

In [10]:
arr = np.array([1,2,3])

In [11]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [12]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [13]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [14]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [15]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [16]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]
