In [1]:
import numpy as np

In [11]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [12]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [13]:
arr2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

### ```np.concatenate((a, b), axis=0)```

In [14]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [15]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [16]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [17]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [18]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [19]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [26]:
arr = np.random.rand(4,4)
arr

array([[0.08113895, 0.8758295 , 0.41563391, 0.91516036],
       [0.71862351, 0.13248434, 0.74839685, 0.87468862],
       [0.43239339, 0.80769794, 0.20042994, 0.02609405],
       [0.66218738, 0.90117229, 0.29390446, 0.01827885]])

In [24]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.96769996, 0.73225211, 0.63405274, 0.2297081 ],
       [0.19367847, 0.04147568, 0.45964941, 0.48277291]]), array([[0.17285678, 0.20898924, 0.86823153, 0.14086691],
       [0.29809034, 0.82532889, 0.70756304, 0.22470115]])]


In [ ]:
array([[0.96769996, 0.73225211, 0.63405274, 0.2297081 ],
       [0.19367847, 0.04147568, 0.45964941, 0.48277291]])

In [ ]:
array([[0.17285678, 0.20898924, 0.86823153, 0.14086691],
       [0.29809034, 0.82532889, 0.70756304, 0.22470115]])

In [27]:
arr

array([[0.08113895, 0.8758295 , 0.41563391, 0.91516036],
       [0.71862351, 0.13248434, 0.74839685, 0.87468862],
       [0.43239339, 0.80769794, 0.20042994, 0.02609405],
       [0.66218738, 0.90117229, 0.29390446, 0.01827885]])

In [28]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.08113895, 0.8758295 ],
       [0.71862351, 0.13248434],
       [0.43239339, 0.80769794],
       [0.66218738, 0.90117229]]), array([[0.41563391, 0.91516036],
       [0.74839685, 0.87468862],
       [0.20042994, 0.02609405],
       [0.29390446, 0.01827885]])]


In [ ]:
array([[0.08113895, 0.8758295 ],
       [0.71862351, 0.13248434],
       [0.43239339, 0.80769794],
       [0.66218738, 0.90117229]])

In [ ]:
array([[0.41563391, 0.91516036],
       [0.74839685, 0.87468862],
       [0.20042994, 0.02609405],
       [0.29390446, 0.01827885]])