In [1]:
import pandas as pd,numpy as np

In [2]:
# Step 1:
df = pd.read_csv("titanic.csv")

In [3]:
df.head(2)

pclass  survived                            name     sex      age  sibsp  \
0     1.0       1.0   Allen, Miss. Elisabeth Walton  female  29.0000    0.0   
1     1.0       1.0  Allison, Master. Hudson Trevor    male   0.9167    1.0   

   parch  ticket      fare    cabin embarked boat  body  \
0    0.0   24160  211.3375       B5        S    2   NaN   
1    2.0  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

In [4]:
df.tail(2)

pclass  survived                name   sex   age  sibsp  parch  ticket  \
1308     3.0       0.0  Zimmerman, Mr. Leo  male  29.0    0.0    0.0  315082   
1309     NaN       NaN                 NaN   NaN   NaN    NaN    NaN     NaN   

       fare cabin embarked boat  body home.dest  
1308  7.875   NaN        S  NaN   NaN       NaN  
1309    NaN   NaN      NaN  NaN   NaN       NaN

In [5]:
df.shape

(1310, 14)

In [6]:
# Step2:

In [7]:
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   float64
 1   survived   1309 non-null   float64
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   float64
 6   parch      1309 non-null   float64
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(7), object(7)
memory usage: 143.4+ KB


In [9]:
df.dtypes

pclass       float64
survived     float64
name          object
sex           object
age          float64
sibsp        float64
parch        float64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [10]:
# Step3: 

In [11]:
df.isnull().sum()*100/len(df)

pclass        0.076336
survived      0.076336
name          0.076336
sex           0.076336
age          20.152672
sibsp         0.076336
parch         0.076336
ticket        0.076336
fare          0.152672
cabin        77.480916
embarked      0.229008
boat         62.900763
body         90.763359
home.dest    43.129771
dtype: float64

In [12]:
df.drop(['cabin','boat','body','home.dest'],axis = 1, inplace = True)

In [13]:
df.isnull().sum()*100/len(df)

pclass       0.076336
survived     0.076336
name         0.076336
sex          0.076336
age         20.152672
sibsp        0.076336
parch        0.076336
ticket       0.076336
fare         0.152672
embarked     0.229008
dtype: float64

In [14]:
df['embarked'].value_counts()

S    914
C    270
Q    123
Name: embarked, dtype: int64

In [15]:
df['embarked'].fillna(df['embarked'].mode(),inplace = True)

In [16]:
df.isnull().sum()*100/len(df)

pclass       0.076336
survived     0.076336
name         0.076336
sex          0.076336
age         20.152672
sibsp        0.076336
parch        0.076336
ticket       0.076336
fare         0.152672
embarked     0.229008
dtype: float64

In [17]:
df['age'].fillna(df['age'].median(),inplace = True)

In [18]:
df.isnull().sum()*100/len(df)

pclass      0.076336
survived    0.076336
name        0.076336
sex         0.076336
age         0.000000
sibsp       0.076336
parch       0.076336
ticket      0.076336
fare        0.152672
embarked    0.229008
dtype: float64

In [19]:
df.dropna(inplace=True)

In [20]:
df.isnull().sum()*100/len(df)

pclass      0.0
survived    0.0
name        0.0
sex         0.0
age         0.0
sibsp       0.0
parch       0.0
ticket      0.0
fare        0.0
embarked    0.0
dtype: float64

In [21]:
df.shape

(1306, 10)

In [22]:
del df['name']

In [23]:
df.head()

pclass  survived     sex      age  sibsp  parch  ticket      fare embarked
0     1.0       1.0  female  29.0000    0.0    0.0   24160  211.3375        S
1     1.0       1.0    male   0.9167    1.0    2.0  113781  151.5500        S
2     1.0       0.0  female   2.0000    1.0    2.0  113781  151.5500        S
3     1.0       0.0    male  30.0000    1.0    2.0  113781  151.5500        S
4     1.0       0.0  female  25.0000    1.0    2.0  113781  151.5500        S

In [24]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [25]:
df['sex'] = label_encoder.fit_transform(df['sex'])

In [26]:
df['embarked'] = label_encoder.fit_transform(df['embarked'])

In [27]:
df.head()

pclass  survived  sex      age  sibsp  parch  ticket      fare  embarked
0     1.0       1.0    0  29.0000    0.0    0.0   24160  211.3375         2
1     1.0       1.0    1   0.9167    1.0    2.0  113781  151.5500         2
2     1.0       0.0    0   2.0000    1.0    2.0  113781  151.5500         2
3     1.0       0.0    1  30.0000    1.0    2.0  113781  151.5500         2
4     1.0       0.0    0  25.0000    1.0    2.0  113781  151.5500         2

In [28]:
abs(df.corr())

pclass  survived       sex       age     sibsp     parch  \
pclass    1.000000  0.310064  0.121407  0.378305  0.060149  0.017596   
survived  0.310064  1.000000  0.527248  0.045756  0.027228  0.083400   
sex       0.121407  0.527248  1.000000  0.055929  0.110529  0.214179   
age       0.378305  0.045756  0.055929  1.000000  0.188884  0.124578   
sibsp     0.060149  0.027228  0.110529  0.188884  1.000000  0.373281   
parch     0.017596  0.083400  0.214179  0.124578  0.373281  1.000000   
fare      0.557861  0.242960  0.184034  0.177627  0.161030  0.222327   
embarked  0.187027  0.176489  0.099090  0.066432  0.066299  0.045438   

              fare  embarked  
pclass    0.557861  0.187027  
survived  0.242960  0.176489  
sex       0.184034  0.099090  
age       0.177627  0.066432  
sibsp     0.161030  0.066299  
parch     0.222327  0.045438  
fare      1.000000  0.239086  
embarked  0.239086  1.000000

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
df.head()

pclass  survived  sex      age  sibsp  parch  ticket      fare  embarked
0     1.0       1.0    0  29.0000    0.0    0.0   24160  211.3375         2
1     1.0       1.0    1   0.9167    1.0    2.0  113781  151.5500         2
2     1.0       0.0    0   2.0000    1.0    2.0  113781  151.5500         2
3     1.0       0.0    1  30.0000    1.0    2.0  113781  151.5500         2
4     1.0       0.0    0  25.0000    1.0    2.0  113781  151.5500         2

In [31]:
del df['ticket']

In [32]:
y = df['survived']
X = df.drop('survived',1)

/var/folders/dq/452wvgp96nv2qcc3dn0dv8240000gn/T/ipykernel_1171/484089062.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop('survived',1)


In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8 , random_state=100)

In [34]:
from sklearn.linear_model import LogisticRegression

In [37]:
model = LogisticRegression()
fit1  = model.fit(X_train,y_train)
pred = fit1.predict(X_test)

In [40]:
pred

array([0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0.

In [41]:
pred_prob = fit1.predict_proba(X_test)

In [43]:
pred_prob[:,0]

array([0.94358758, 0.19402658, 0.80760995, 0.89342916, 0.24542268,
       0.851559  , 0.12681631, 0.79787892, 0.37210028, 0.85719937,
       0.74503676, 0.85704857, 0.72032989, 0.06608704, 0.82175682,
       0.86464314, 0.73457946, 0.86281301, 0.73242872, 0.81459366,
       0.87735994, 0.79460117, 0.41179967, 0.62996237, 0.37923564,
       0.37209333, 0.89977929, 0.54886747, 0.71279116, 0.17555665,
       0.8552473 , 0.87222399, 0.64283599, 0.28592639, 0.54911002,
       0.88743198, 0.1763015 , 0.83399587, 0.5322166 , 0.88608167,
       0.73330043, 0.13266446, 0.86621294, 0.3688741 , 0.92571473,
       0.8624231 , 0.66416816, 0.52465337, 0.17779633, 0.37203957,
       0.17028804, 0.46719698, 0.93805571, 0.37647323, 0.87455904,
       0.60641513, 0.43749656, 0.54734553, 0.0672002 , 0.05533526,
       0.73878191, 0.20044351, 0.34878205, 0.22223897, 0.38667061,
       0.75708387, 0.14779227, 0.37824633, 0.8463419 , 0.84028115,
       0.69071504, 0.87380143, 0.31710403, 0.24446747, 0.20099

In [44]:
pred_prob[:,1]

array([0.05641242, 0.80597342, 0.19239005, 0.10657084, 0.75457732,
       0.148441  , 0.87318369, 0.20212108, 0.62789972, 0.14280063,
       0.25496324, 0.14295143, 0.27967011, 0.93391296, 0.17824318,
       0.13535686, 0.26542054, 0.13718699, 0.26757128, 0.18540634,
       0.12264006, 0.20539883, 0.58820033, 0.37003763, 0.62076436,
       0.62790667, 0.10022071, 0.45113253, 0.28720884, 0.82444335,
       0.1447527 , 0.12777601, 0.35716401, 0.71407361, 0.45088998,
       0.11256802, 0.8236985 , 0.16600413, 0.4677834 , 0.11391833,
       0.26669957, 0.86733554, 0.13378706, 0.6311259 , 0.07428527,
       0.1375769 , 0.33583184, 0.47534663, 0.82220367, 0.62796043,
       0.82971196, 0.53280302, 0.06194429, 0.62352677, 0.12544096,
       0.39358487, 0.56250344, 0.45265447, 0.9327998 , 0.94466474,
       0.26121809, 0.79955649, 0.65121795, 0.77776103, 0.61332939,
       0.24291613, 0.85220773, 0.62175367, 0.1536581 , 0.15971885,
       0.30928496, 0.12619857, 0.68289597, 0.75553253, 0.79900